version: '3.8'

services:
  # PHP with Apache server
  php:
    build: .
    container_name: php_container
    ports:
      - "8080:80"
    volumes:
      - ./Logintest:/var/www/logintest
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: login
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # phpMyAdmin for managing MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
